In [2]:
import pandas as pd
import os

In [3]:
"""
Primero importar amr y filtrar por AMR de las familias de importancias, luego  

Tengo que tomar entero base, con sus barcode y quedar
"""
db = pd.read_csv(os.path.join("out", "amr.tsv"), sep='\t')
db = db.drop(columns=['HC50', 'SISTR1 Serovar HC20', 'SISTR1 Serovar HC50'])
db

,Assembly Barcode,Resistance gene,Class,SISTR1 Serovar,HC20,Source Niche,Collection Year
0,SAL_AD8849AA_AS,floR,PHENICOL,Adelaide,302263,Environment,2022
1,SAL_AD8849AA_AS,blaTEM-1,BETA-LACTAM,Adelaide,302263,Environment,2022
2,SAL_AD8849AA_AS,dfrA12,TRIMETHOPRIM,Adelaide,302263,Environment,2022
3,SAL_AD8849AA_AS,aadA2,AMINOGLYCOSIDE,Adelaide,302263,Environment,2022
4,SAL_AD8849AA_AS,sul1,SULFONAMIDE,Adelaide,302263,Environment,2022
...,...,...,...,...,...,...,...
2150,SAL_DC0019AA_AS,blaCARB-2,BETA-LACTAM,Typhimurium,305,Environment,2019
2151,SAL_DC0019AA_AS,sul1,SULFONAMIDE,Typhimurium,305,Environment,2019
2152,SAL_DC0019AA_AS,aadA2,AMINOGLYCOSIDE,Typhimurium,305,Environment,2019
2153,SAL_OC0804AA_AS,tet(G),TETRACYCLINE,Typhimurium,305,Environment,2019
2154,SAL_DC9664AA_AS,qnrB,QUINOLONE,Worthington,147475,Environment,2019

In [4]:
FAMILIAS = ['QUINOLONE', 'BETA-LACTAM', 'MACROLIDE', 'TRIMETHOPRIM']
SEROTIPOS = ['Typhimurium', 'Newport', 'Enteritidis', 'Infantis', 'I 1,4,[5],12:i:-', 'Agona']

### AMR

In [5]:
amr = db[db['Class'].isin(FAMILIAS)]
print(amr.shape[0])
amr = amr[amr['SISTR1 Serovar'].isin(SEROTIPOS)]
print(amr.shape[0])
amr = amr.set_index('Assembly Barcode')
amr

598
524

,Resistance gene,Class,SISTR1 Serovar,HC20,Source Niche,Collection Year
Assembly Barcode,,,,,,
SAL_QD2199AA_AS,blaTEM-1,BETA-LACTAM,Agona,419,Environment,2022
SAL_QD2199AA_AS,qnrS1,QUINOLONE,Agona,419,Environment,2022
SAL_ZC7016AA_AS,dfrA17,TRIMETHOPRIM,Agona,419,Companion Animal,2021
SAL_JC3732AA_AS,blaTEM-1,BETA-LACTAM,Agona,419,Food,2018
SAL_DC0057AA_AS,blaTEM-1,BETA-LACTAM,Agona,419,Environment,2019
...,...,...,...,...,...,...
SAL_MB2490AA_AS,blaCARB-2,BETA-LACTAM,Typhimurium,305,Livestock,2016
SAL_MB2476AA_AS,blaCARB-2,BETA-LACTAM,Typhimurium,305,Environment,2016
SAL_MB2470AA_AS,blaCARB-2,BETA-LACTAM,Typhimurium,305,Environment,2015
SAL_PD4169AA_AS,blaCARB-2,BETA-LACTAM,Typhimurium,305,Environment,2022
SAL_DC0019AA_AS,blaCARB-2,BETA-LACTAM,Typhimurium,305,Environment,2019

### Abricate

In [6]:
abricate = pd.read_csv("out/abricate_summary.tsv", sep='\t')
abricate = abricate.set_index("Assembly Barcode")
abricate.to_csv("XXX")
abricate

,Col(MG828)_1,Col(VCM04)_1,Col(Ye4449)_1,Col(pB8919)_1,Col(pHAD28)_1,Col156_1,Col3M_1,Col440II_1,Col440I_1,ColE10_1,...,IncX3_1,IncX4_1,IncX4_2,IncY_1,p0111_1,pEC4115_1,pESA2_1,pKPC-CAV1321_1,repB(R1701)_1,repE(pEh60-7)_1
Assembly Barcode,,,,,,,,,,,,,,,,,,,,,
SAL_AC6595AA_AS,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SAL_AC6596AA_AS,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
SAL_AC6597AA_AS,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SAL_AC6600AA_AS,0,0,0,0,1,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
SAL_AC7029AA_AS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAL_ZC9426AA_AS,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
SAL_ZC9427AA_AS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SAL_ZC9428AA_AS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SAL_ZC9429AA_AS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SAL_ZC9430AA_AS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
nuevas_filas = []
for barcode, fila in abricate.iterrows():
    for gen, valor in fila.items():
        if valor == 1:
            nuevas_filas.append([barcode, gen])
nuevo_df = pd.DataFrame(nuevas_filas, columns=['Assembly Barcode', 'Amplicon'])
nuevo_df

     Assembly Barcode           Amplicon
0     SAL_AC6595AA_AS      Col(pHAD28)_1
1     SAL_AC6596AA_AS          ColRNAI_1
2     SAL_AC6596AA_AS        IncFIB(S)_1
3     SAL_AC6596AA_AS        IncFII(S)_1
4     SAL_AC6596AA_AS  IncFII(pAR0022)_1
...               ...                ...
1517  SAL_ZC9426AA_AS            IncX4_2
1518  SAL_ZC9427AA_AS  IncFIB(pN55391)_1
1519  SAL_ZC9428AA_AS  IncFIB(pN55391)_1
1520  SAL_ZC9429AA_AS  IncFIB(pN55391)_1
1521  SAL_ZC9430AA_AS  IncFIB(pN55391)_1

[1522 rows x 2 columns]

# Merge n export

In [8]:
df_merge = pd.merge(nuevo_df, amr, on='Assembly Barcode', how='right')
df_merge['Amplicon'] = df_merge['Amplicon'].fillna('No_plasmid')

df_merge = df_merge.rename(columns={'Resistance gene': 'AMR', 'SISTR1 Serovar': 'Serovar', 'Source Niche': 'Niche', 'Collection Year': 'Year'})

df_merge = df_merge.drop(columns=['Assembly Barcode', 'AMR'])
df_merge.to_csv("out/MCA_table_v1.csv", index=False)
df_merge

              Amplicon        Class      Serovar  HC20        Niche  Year
0             Col156_1  BETA-LACTAM        Agona   419  Environment  2022
1            ColRNAI_1  BETA-LACTAM        Agona   419  Environment  2022
2          IncFIB(K)_1  BETA-LACTAM        Agona   419  Environment  2022
3             Col156_1    QUINOLONE        Agona   419  Environment  2022
4            ColRNAI_1    QUINOLONE        Agona   419  Environment  2022
..                 ...          ...          ...   ...          ...   ...
683           Col156_1  BETA-LACTAM  Typhimurium   305  Environment  2019
684          ColRNAI_1  BETA-LACTAM  Typhimurium   305  Environment  2019
685        IncFIB(S)_1  BETA-LACTAM  Typhimurium   305  Environment  2019
686        IncFII(S)_1  BETA-LACTAM  Typhimurium   305  Environment  2019
687  IncFII(pAR0022)_1  BETA-LACTAM  Typhimurium   305  Environment  2019

[688 rows x 6 columns]

In [15]:
df_merge = pd.merge(nuevo_df, amr, on='Assembly Barcode', how='right')
df_merge['Amplicon'] = df_merge['Amplicon'].fillna('No_plasmid')
df_merge = df_merge.rename(columns={'Resistance gene': 'AMR', 'SISTR1 Serovar': 'Serovar', 'Source Niche': 'Niche', 'Collection Year': 'Year', 'Amplicon': 'Plmd'})

df_merge = df_merge.drop(columns=['Assembly Barcode', 'AMR'])
df_merge.to_csv("out/MCA_table_v2.csv", index=False)
len(df_merge['Serovar'].unique())

6

#### Por serotipos

In [10]:
SEROTIPOS = ['Typhimurium', 'Newport', 'Enteritidis', 'Infantis', 'I 1,4,[5],12:i:-', 'Agona']
SEROTIPOS = ['Typhimurium', 'Newport', 'Enteritidis', 'Infantis', 'I 1,4,[5],12:i:-']

In [11]:
def mca_oly_serovar(df, serotipo):
    df = df[df['Serovar'] == serotipo]
    df = df.drop(columns=['Serovar'])
    df.to_csv(f"out/MCA_table_for_{serotipo}.csv", index=False)

for ser in SEROTIPOS:
    mca_oly_serovar(df_merge, ser)

In [12]:
def mca_oly_serovar(df, serotipo):
    df = df[df['Serovar'] == serotipo]
    df = df.drop(columns=['Serovar', 'Niche'])
    df.to_csv(f"out/MCA_table_for_{serotipo}.csv", index=False)
mca_oly_serovar(df_merge, 'Newport')